/**
 * sessions.js — FIXES:
 *
 * 1. Ad-hoc lecture creation: when a session is started at an "odd hour"
 *    (no matching scheduled lecture within ±30 min), a new lecture entry
 *    is appended to Course.lectures with scheduledTime = now and a sensible
 *    duration window. The session is then linked to that lectureUID.
 *    This way analytics always has a proper lecture to group sessions under.
 *
 * 2. Active session uses active:true flag (from previous fix).
 *
 * 3. Lecture matching window: ±30 minutes around now to catch slightly
 *    late/early session starts without creating spurious lectures.
 */
const express  = require('express');
const { v4: uuidv4 } = require('uuid');
const Session  = require('../models/Session');
const Course   = require('../models/Course');
const { authenticate } = require('../middleware/auth');

const router = express.Router();

const LECTURE_MATCH_WINDOW_MS = 30 * 60 * 1000; // ±30 min
const DEFAULT_LECTURE_DURATION_MIN = 55;          // typical class length

// ── Resolve or create a lecture for an ad-hoc session ─────────────────────────
/**
 * Finds the best matching lecture in course.lectures for the current time.
 * If none found within ±30 min, creates a new one on the Course document.
 *
 * Returns { lectureUID, scheduledTime, wasCreated }
 */
async function resolveOrCreateLecture(course, providedLectureUID) {
  const now = new Date();

  // 1. If caller explicitly provided a lectureUID, use it
  if (providedLectureUID) {
    const lec = course.lectures.find(l => l.lectureUID === providedLectureUID);
    if (lec) return { lectureUID: lec.lectureUID, scheduledTime: lec.scheduledTime, wasCreated: false };
    // Provided UID not found — fall through to auto-resolve
  }

  // 2. Find the closest non-cancelled lecture within the window
  const window = LECTURE_MATCH_WINDOW_MS;
  const closest = course.lectures
    .filter(l => !l.cancelled)
    .map(l => ({ ...l, diff: Math.abs(new Date(l.scheduledTime) - now) }))
    .filter(l => l.diff <= window)
    .sort((a, b) => a.diff - b.diff)[0];

  if (closest) {
    return { lectureUID: closest.lectureUID, scheduledTime: closest.scheduledTime, wasCreated: false };
  }

  // 3. No match — create an ad-hoc lecture on the Course document
  // Round scheduledTime down to the nearest minute for cleanliness
  const scheduledTime = new Date(Math.floor(now.getTime() / 60000) * 60000);
  const lectureUID    = uuidv4();

  await Course.updateOne(
    { _id: course._id },
    {
      $push: {
        lectures: {
          lectureUID,
          scheduledTime,
          cancelled: false,
        },
      },
    }
  );

  console.log(`[Session] Created ad-hoc lecture ${lectureUID} for course ${course._id} at ${scheduledTime.toISOString()}`);
  return { lectureUID, scheduledTime, wasCreated: true };
}

// ── POST /startSession ────────────────────────────────────────────────────────
router.post('/startSession', authenticate, async (req, res, next) => {
  try {
    const { course_id, mode, lectureUID } = req.body;
    if (!course_id || !mode) {
      return res.status(400).json({ error: 'course_id and mode are required' });
    }

    const course = await Course.findById(course_id).lean();
    if (!course) return res.status(404).json({ error: 'Course not found' });

    const uid     = req.user.user_id;
    const allowed = req.user.role === 'admin'
      || course.instructors.includes(uid)
      || (course.tas || []).includes(uid);
    if (!allowed) return res.status(403).json({ error: 'Forbidden' });

    // Resolve (or create) the lecture this session belongs to
    const { lectureUID: resolvedUID, scheduledTime, wasCreated } =
      await resolveOrCreateLecture(course, lectureUID);

    // Guard: no duplicate active session for same (course, lectureUID, method)
    const existing = await Session.findOne({
      course:     course_id,
      lectureUID: resolvedUID,
      method:     mode,
      active:     true,
    }).lean();

    if (existing) {
      return res.status(409).json({
        error:      `An active ${mode} session already exists for this lecture`,
        session_id: existing.sessionUID,
      });
    }

    const session = await Session.create({
      course:          course_id,
      lectureUID:      resolvedUID,
      scheduledTime,
      duration:        DEFAULT_LECTURE_DURATION_MIN,
      method:          mode,
      isAutoGenerated: false,
      active:          true,
    });

    res.status(201).json({
      session_id:   session.sessionUID,
      lectureUID:   resolvedUID,
      method:       mode,
      lectureCreated: wasCreated, // tells the frontend if a new lecture was made
    });
  } catch (err) { next(err); }
});

// ── POST /endSession/:sessionId ───────────────────────────────────────────────
router.post('/endSession/:sessionId', authenticate, async (req, res, next) => {
  try {
    const session = await Session.findOneAndUpdate(
      { sessionUID: req.params.sessionId },
      { $set: { active: false, endedAt: new Date() } },
      { new: true }
    );
    if (!session) return res.status(404).json({ error: 'Session not found' });
    res.json({ message: 'Session ended', session_id: session.sessionUID });
  } catch (err) { next(err); }
});

// ── GET /activeSession?course_id=... ─────────────────────────────────────────
router.get('/activeSession', authenticate, async (req, res, next) => {
  try {
    const { course_id } = req.query;
    if (!course_id) return res.status(400).json({ error: 'course_id required' });

    const sessions = await Session.find({ course: course_id, active: true })
      .sort({ timestamp: -1 })
      .lean();

    if (sessions.length === 0) return res.json({});

    const primary = sessions[0];
    res.json({
      session_id:     primary.sessionUID,
      method:         primary.method,
      lectureUID:     primary.lectureUID,
      startedAt:      primary.timestamp,
      activeSessions: sessions.map(s => ({
        session_id: s.sessionUID,
        method:     s.method,
        lectureUID: s.lectureUID,
        startedAt:  s.timestamp,
      })),
    });
  } catch (err) { next(err); }
});

// ── GET /admin/sessions ───────────────────────────────────────────────────────
router.get('/admin/sessions', authenticate, async (req, res, next) => {
  try {
    if (req.user.role !== 'admin') return res.status(403).json({ error: 'Forbidden' });
    const sessions = await Session.find().sort({ timestamp: -1 }).limit(200).lean();
    res.json(sessions.map(s => ({
      ...s,
      session_id: s.sessionUID,
      course_id:  s.course,
    })));
  } catch (err) { next(err); }
});

module.exports = router;