/**
 * generate_test_csvs.js
 *
 * Generates CSV files for testing every bulk-create and bulk-delete
 * operation in DIAMS. Run once with:
 *
 *   node generate_test_csvs.js
 *
 * Output files (written to ./csv_tests/):
 *
 *  CREATE
 *   professors_create.csv     — 3 new professors
 *   students_create.csv       — 10 new students
 *   courses_create.csv        — 3 new courses (refs the professors & students above)
 *   enrollments_create.csv    — enrolls the new students into the new courses
 *
 *  DELETE  (only the columns the backend actually reads)
 *   professors_delete.csv     — deletes the 3 professors created above
 *   students_delete.csv       — deletes the 10 students created above
 *   courses_delete.csv        — deletes the 3 courses created above
 *   enrollments_delete.csv    — drops the enrollments created above
 *
 * Recommended test order
 * ──────────────────────
 *  1. professors_create  2. students_create  3. courses_create  4. enrollments_create
 *  5. Verify in UI / Analytics
 *  6. enrollments_delete  7. courses_delete  8. students_delete  9. professors_delete
 */

const fs   = require('fs');
const path = require('path');

const OUT = path.join(__dirname, 'csv_tests');
fs.mkdirSync(OUT, { recursive: true });

// ── tiny CSV writer ────────────────────────────────────────────────────────────
function writeCsv(filename, rows) {
  if (!rows.length) return;
  const headers = Object.keys(rows[0]);
  const lines   = [
    headers.join(','),
    ...rows.map(r =>
      headers.map(h => {
        const v = String(r[h] ?? '');
        return v.includes(',') || v.includes('"')
          ? `"${v.replace(/"/g, '""')}"`
          : v;
      }).join(',')
    ),
  ];
  fs.writeFileSync(path.join(OUT, filename), lines.join('\n') + '\n');
  console.log(`  written  ${filename}  (${rows.length} rows)`);
}

// ═══════════════════════════════════════════════════════════════════════════════
// DATA
// ═══════════════════════════════════════════════════════════════════════════════

// ── Professors ────────────────────────────────────────────────────────────────
// Required: _id  name  email  password
// Optional: department
const PROFESSORS = [
  { _id: 'prof_test01', name: 'Prof. Testson',  email: 'testson@iith.ac.in',  password: 'prof123', department: 'CSE' },
  { _id: 'prof_test02', name: 'Prof. Bulkmann', email: 'bulkmann@iith.ac.in', password: 'prof123', department: 'EE'  },
  { _id: 'prof_test03', name: 'Prof. Csvpath',  email: 'csvpath@iith.ac.in',  password: 'prof123', department: 'MA'  },
];

// ── Students ──────────────────────────────────────────────────────────────────
// Required: _id  name  email  password
// Optional: imageURL  (blank = DiceBear avatar auto-generated by backend)
const STUDENTS = [
  { _id: 'TST001', name: 'Alice Tester',   email: 'tst001@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST002', name: 'Bob Bulkload',   email: 'tst002@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST003', name: 'Carol Comma',    email: 'tst003@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST004', name: 'Dave Delimiter', email: 'tst004@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST005', name: 'Eve Enrollee',   email: 'tst005@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST006', name: 'Frank Fields',   email: 'tst006@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST007', name: 'Grace Grid',     email: 'tst007@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST008', name: 'Hank Header',    email: 'tst008@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST009', name: 'Ivy Import',     email: 'tst009@iith.ac.in', password: 'stud123', imageURL: '' },
  { _id: 'TST010', name: 'Jake JsonFail',  email: 'tst010@iith.ac.in', password: 'stud123', imageURL: '' },
];

// ── Courses ───────────────────────────────────────────────────────────────────
// Required: _id  name  department  slot  venue  startDate  endDate
// Optional: instructors  tas
//   instructors — comma-separated professor _ids inside the cell
//   tas         — comma-separated student  _ids inside the cell (blank = none)
// slot must be one of: A B C D E F G P Q R S W X Y Z
// venue must match an existing Classroom _id (LH-1 / LH-2 / LH-7 / LH-12 from seed)
// The backend auto-generates all lecture slots via populateLectures().
const COURSES = [
  {
    _id:         'TST_CS101',
    name:        'Test: Intro to Computing',
    department:  'CSE',
    slot:        'D',                        // Mon 12:00  Tue 09:00  Fri 11:00
    venue:       'LH-1',
    startDate:   '2026-01-01',
    endDate:     '2026-04-30',
    instructors: 'prof_test01',
    tas:         'TST001,TST002',            // two TAs
  },
  {
    _id:         'TST_EE201',
    name:        'Test: Circuit Theory',
    department:  'EE',
    slot:        'F',                        // Tue 11:00  Wed 14:30  Fri 10:00
    venue:       'LH-7',
    startDate:   '2026-01-01',
    endDate:     '2026-04-30',
    instructors: 'prof_test02',
    tas:         'TST003',                   // one TA
  },
  {
    _id:         'TST_MA301',
    name:        'Test: Probability & Stats',
    department:  'MA',
    slot:        'G',                        // Tue 12:00  Wed 12:00  Fri 12:00
    venue:       'LH-12',
    startDate:   '2026-01-01',
    endDate:     '2026-04-30',
    instructors: 'prof_test01,prof_test03',  // two instructors
    tas:         '',                         // no TAs
  },
];

// ── Enrollments ───────────────────────────────────────────────────────────────
// Required: student (student _id)  course (course _id)
// Backend upserts — safe to run multiple times (idempotent).
//
// Spread (intentional overlaps to test multi-course enrollment):
//   TST_CS101  → TST001 TST002 TST003 TST004 TST005
//   TST_EE201  → TST004 TST005 TST006 TST007 TST008
//   TST_MA301  → TST007 TST008 TST009 TST010
const ENROLLMENTS = [
  ...['TST001','TST002','TST003','TST004','TST005'].map(s => ({ student: s, course: 'TST_CS101' })),
  ...['TST004','TST005','TST006','TST007','TST008'].map(s => ({ student: s, course: 'TST_EE201' })),
  ...['TST007','TST008','TST009','TST010'         ].map(s => ({ student: s, course: 'TST_MA301' })),
];

// ═══════════════════════════════════════════════════════════════════════════════
// WRITE CREATE CSVs
// ═══════════════════════════════════════════════════════════════════════════════
console.log('\nGenerating CREATE CSVs…');
writeCsv('professors_create.csv',  PROFESSORS);
writeCsv('students_create.csv',    STUDENTS);
writeCsv('courses_create.csv',     COURSES);
writeCsv('enrollments_create.csv', ENROLLMENTS);

// ═══════════════════════════════════════════════════════════════════════════════
// WRITE DELETE CSVs
// ═══════════════════════════════════════════════════════════════════════════════
// students / professors / courses  → only _id column is needed
// enrollments                      → student + course columns are needed
console.log('\nGenerating DELETE CSVs…');
writeCsv('professors_delete.csv',  PROFESSORS.map(p => ({ _id: p._id })));
writeCsv('students_delete.csv',    STUDENTS.map(s => ({ _id: s._id })));
writeCsv('courses_delete.csv',     COURSES.map(c => ({ _id: c._id })));
writeCsv('enrollments_delete.csv', ENROLLMENTS);   // student+course already present

// ═══════════════════════════════════════════════════════════════════════════════
// SUMMARY
// ═══════════════════════════════════════════════════════════════════════════════
console.log(`
All files written to: ${OUT}

Recommended test order
──────────────────────
Step  Action         File                      type param
 1    Bulk Create    professors_create.csv     professors
 2    Bulk Create    students_create.csv       students
 3    Bulk Create    courses_create.csv        courses
 4    Bulk Create    enrollments_create.csv    enrollments
 5    ── verify in Admin UI, Analytics, Students pages ──
 6    Bulk Delete    enrollments_delete.csv    enrollments
 7    Bulk Delete    courses_delete.csv        courses
 8    Bulk Delete    students_delete.csv       students
 9    Bulk Delete    professors_delete.csv     professors

Edge cases covered
──────────────────
  Multi-instructor course   TST_MA301 has two instructors (comma-sep in one cell)
  No-TA course              TST_MA301 has an empty tas column
  Multi-TA course           TST_CS101 has two TAs
  Multi-course students     TST004/005/007/008 are enrolled in two courses each
  Idempotent enrollments    Re-uploading enrollments_create upserts safely
  Safe deletes              Deleting non-existent _ids returns 0 deleted, no error
`);
