/**
 * autoSessionService.js
 *
 * Runs every minute via cron.
 * Creates a fallback 5-min BLE session for any lecture due right now
 * that has no active scheduled session covering it.
 *
 * Timezone contract (after lecturePopulator fix):
 *   - lecture.scheduledTime  : UTC timestamp
 *   - schedule.startTime/endTime : IST strings ("HH:mm")
 *   - schedule.scheduledDay      : IST day name ("Monday" etc.)
 *
 * So we convert "now" and lecture times to IST for all comparisons.
 */
const Course   = require('../models/Course');
const Session  = require('../models/Session');

const DAY_NAMES      = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const IST_OFFSET_MS  = 5.5 * 60 * 60 * 1000; // 19 800 000 ms

/** Return IST components of a UTC Date */
function toIST(utcDate) {
  const d = new Date(utcDate.getTime() + IST_OFFSET_MS);
  return {
    dayName: DAY_NAMES[d.getUTCDay()],
    totalMin: d.getUTCHours() * 60 + d.getUTCMinutes(),
  };
}

async function autoCreateFallbackSessions() {
  const now         = new Date();
  const windowStart = new Date(now.getTime() - 2 * 60000);
  const windowEnd   = new Date(now.getTime() + 2 * 60000);

  const { dayName: todayName } = toIST(now);

  const courses = await Course.find({
    'lectures.scheduledTime': { $gte: windowStart, $lte: windowEnd },
    'lectures.cancelled':     false,
  }).lean();

  for (const course of courses) {
    const dueLectures = course.lectures.filter(l =>
      !l.cancelled &&
      new Date(l.scheduledTime) >= windowStart &&
      new Date(l.scheduledTime) <= windowEnd
    );

    for (const lecture of dueLectures) {
      // Convert stored UTC scheduledTime to IST for schedule comparison
      const { dayName: lecDayName, totalMin: lecMin } = toIST(new Date(lecture.scheduledTime));

      // Check if a schedule entry covers this lecture time
      const covered = (course.schedules || []).some(s => {
        if (s.scheduledDay !== lecDayName) return false;
        const [sh, sm] = s.startTime.split(':').map(Number); // IST
        const [eh, em] = s.endTime.split(':').map(Number);   // IST
        return lecMin >= sh * 60 + sm && lecMin < eh * 60 + em;
      });

      if (covered) continue;

      const existing = await Session.findOne({
        course:     course._id,
        lectureUID: lecture.lectureUID,
        active:     true,
      }).lean();

      if (existing) continue;

      await Session.create({
        course:          course._id,
        lectureUID:      lecture.lectureUID,
        scheduledTime:   lecture.scheduledTime,
        duration:        5,
        method:          'BLE',
        isAutoGenerated: true,
        active:          true,
      });

      console.log(`[AutoSession] 5-min BLE fallback for ${course._id} / ${lecture.lectureUID}`);
    }
  }
}

module.exports = { autoCreateFallbackSessions };