const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const SessionSchema = new mongoose.Schema({
  sessionUID: {
    type:    String,
    default: uuidv4,
    unique:  true,
  },
  course: {
    type:     String,
    required: true,
    ref:      'Course',
  },
  lectureUID: {
    type:     String,
    required: true,
    // NOT unique per course — a lecture can have many sessions (BLE + QR, etc.)
  },
  scheduledTime: {
    type:     Date,
    required: true,
  },
  duration: {
    type:     Number, // minutes — kept for reference, no longer used for active check
    required: true,
  },
  method: {
    type:     String,
    enum:     ['BLE', 'QRCode', 'Manual'],
    required: true,
  },
  isAutoGenerated: {
    type:    Boolean,
    default: false,
  },
  // ── Active flag (replaces the duration-based expiry hack) ────────────────────
  // true  = session is currently running
  // false = session was ended (via endSession or auto-expiry cron)
  active: {
    type:    Boolean,
    default: true,
    index:   true,
  },
  endedAt: {
    type:    Date,
    default: null,
  },
  timestamp: {
    type:    Date,
    default: Date.now,
  },
});

// Compound index: most common query pattern
SessionSchema.index({ course: 1, active: 1 });              // GET /activeSession
SessionSchema.index({ course: 1, lectureUID: 1 });           // analytics grouping
SessionSchema.index({ course: 1, lectureUID: 1, method: 1, active: 1 }); // duplicate guard
SessionSchema.index({ sessionUID: 1 }, { unique: true });    // primary lookup
SessionSchema.index({ timestamp: -1 });                      // admin sessions list

module.exports = mongoose.model('Session', SessionSchema);